name: "shop"
version: 1.0.0
config-version: 2

models:
  marts:
    core:
      # materialize all models in models/events as tables
      +materialized: table
    Staging:
      shop:
      # this is redundant, and does not need to be set
      +materialized: view
